baseURL = "https://example.com/"
languageCode = "ru-ru"
title = "Квартирник"
theme = "ananke"
[params]
  featured_image = "/images/RS-88.jpg"
  featured_image_home = "/images/RS-88.jpg"
  featured_image_class = "cover bg-center"
  cover_dimming_class = "bg-black-40"
[menu]

  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Текущий квартирник"
    url = "/current/"
    weight = 2

  [[menu.main]]
    name = "Архив"
    url = "/kvartirniki/"
    weight = 3

  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 4