baseURL = "https://kvartirniknn.ru/"
languageCode = "ru-ru"
title = "КАМИН"
theme = "ananke"

# Добавляем эту строку для отображения будущих страниц
buildFuture = true

[deployment]
[[deployment.targets]]
name = "github-pages"
URL = "github://token=$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@github.com/heeeyMan/Kvartirnik-site.git"
branch = "gh-pages"

[params]
  featured_image = "/images/RS-88.jpg"
  featured_image_home = "/images/RS-88.jpg"
  featured_image_class = "cover bg-center"
  cover_dimming_class = "bg-black-40"
  current_kvartirnik = "2025-10-05"  # Дата активного квартирник
  custom_css = ["css/custom.css"]
  

[frontmatter]
  lastmod = ['lastmod', ':git', 'date']

[build]
  writeStats = true

[menu]

  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Архив"
    url = "/history/"
    weight = 2

  [[menu.main]]
    name = "О нас"
    url = "/about/"
    weight = 3